-- MySQL Script generated by MySQL Workbench
-- Wed Jan 14 10:34:55 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema MA-METIER_projet
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema MA-METIER_projet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MA-METIER_projet` DEFAULT CHARACTER SET utf8 ;
USE `MA-METIER_projet` ;

-- -----------------------------------------------------
-- Table `MA-METIER_projet`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MA-METIER_projet`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(20) NOT NULL,
  `password` VARCHAR(25) NOT NULL, 
  `email` VARCHAR(175) NOT NULL,
  `birthdate` DATE NOT NULL, 
  `age` INT NOT NULL,
  `role` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `unique` (`username` ASC, `email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MA-METIER_projet`.`domains`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MA-METIER_projet`.`domains` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `information` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MA-METIER_projet`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MA-METIER_projet`.`messages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Content` VARCHAR(45) NOT NULL,
  `sending_date` DATE NOT NULL,
  `domains_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_messages_domains1_idx` (`domains_id` ASC) VISIBLE,
  CONSTRAINT `fk_messages_domains1`
    FOREIGN KEY (`domains_id`)
    REFERENCES `MA-METIER_projet`.`domains` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MA-METIER_projet`.`users_send_messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MA-METIER_projet`.`users_send_messages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NULL,
  `messages_id` INT NULL,
  INDEX `fk_users_has_messages_messages1_idx` (`messages_id` ASC) VISIBLE,
  INDEX `fk_users_has_messages_users_idx` (`users_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_users_has_messages_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `MA-METIER_projet`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_messages_messages1`
    FOREIGN KEY (`messages_id`)
    REFERENCES `MA-METIER_projet`.`messages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
